"""NumPy-compatible Python package wrapping the Rust native module."""
import sys as _sys
import math as _stdlib_math
import json as _json
from functools import reduce as _reduce

__version__ = "1.26.0"

# Import from native Rust module
import _numpy_native as _native
from _numpy_native import ndarray
from _numpy_native import dot as _native_dot
from _numpy_native import concatenate as _native_concatenate
from ._helpers import *
from ._core_types import *
from ._datetime import *
from ._creation import *
from ._math import *
from ._reductions import *
from ._manipulation import *
from ._bitwise import *
from ._ufunc import *
from ._ufunc import _ufunc_reconstruct, gcd, lcm
# RustPython treats builtin names like 'divmod' specially in module scope;
# setattr on the module object is the only reliable way to override it.
from ._poly import *
from ._indexing import *
from ._window import *
from ._io import *
from ._stubs import *
from ._string_ops import char, chararray  # override _stubs char with full chararray support
from ._linalg_ext import *
from ._fft_ext import *
from ._random_ext import *


# Import submodules so they're accessible as numpy.linalg etc.
from _numpy_native import linalg, fft, random

# Import numpy.lib so np.lib.mixins etc. work
import numpy.lib as lib

# Register Rust submodules in sys.modules so `from numpy.random import ...` works
_sys.modules["numpy.linalg"] = linalg
_sys.modules["numpy.fft"] = fft
_sys.modules["numpy.random"] = random


# --- Constants --------------------------------------------------------------
nan = float("nan")
inf = float("inf")
pi = _stdlib_math.pi
e = _stdlib_math.e
newaxis = None
PINF = float("inf")
NINF = float("-inf")
PZERO = 0.0
NZERO = -0.0
Inf = inf
Infinity = inf
NaN = nan
NAN = nan
euler_gamma = 0.5772156649015329
ALLOW_THREADS = 1
little_endian = True

# __config__ stub - normally generated by build system
class __config__:
    """Build configuration stub."""
    pass

# numpy 1.x compat: np.bool (deprecated, can't shadow builtin 'bool' in module
# scope since isinstance checks recurse). We set it via __getattr__ below.


# ---------------------------------------------------------------------------
# Wrap native dot to handle non-ndarray inputs (e.g. flatiter)
def dot(a, b, out=None):
    """Dot product of two arrays."""
    if type(a).__name__ == 'flatiter':
        a = asarray(a)
    elif not isinstance(a, ndarray):
        a = asarray(a)
    if type(b).__name__ == 'flatiter':
        b = asarray(b)
    elif not isinstance(b, ndarray):
        b = asarray(b)
    result = _native_dot(a, b)
    if out is not None:
        out[:] = result
        return out
    return result

# ---------------------------------------------------------------------------
# _parse_dtype_json, void scalar, StructuredArray wrapper
# ---------------------------------------------------------------------------

def _parse_dtype_json(json_str):
    """Convert dtype_json string back to StructuredDtype.
    dtype_json format: [["x","float64"],["y","int32"]]
    Returns a StructuredDtype instance.
    """
    from numpy._core_types import StructuredDtype
    pairs = _json.loads(json_str)   # list of [name, dtype_str]
    return StructuredDtype([(name, dt_str) for name, dt_str in pairs])


class void:
    """Scalar returned by arr[i] on a structured array, or a placeholder void of N bytes."""

    def __init__(self, data=None, dtype=None):
        if data is None:
            # np.void() creates an empty void scalar
            object.__setattr__(self, '_data', {})
            object.__setattr__(self, '_bytes', b'')
            object.__setattr__(self, 'dtype', None)
            return
        if isinstance(data, int) and dtype is None:
            # np.void(n) creates a placeholder void of n bytes
            object.__setattr__(self, '_data', {})
            object.__setattr__(self, '_bytes', b'\x00' * data)
            object.__setattr__(self, 'dtype', None)
            return
        if isinstance(data, (bytes, bytearray)) and dtype is None:
            # np.void(b'\x01\x02') creates a void scalar from raw bytes
            object.__setattr__(self, '_data', {})
            object.__setattr__(self, '_bytes', bytes(data))
            object.__setattr__(self, 'dtype', None)
            return
        # Use object.__setattr__ throughout to avoid any __setattr__ override issues
        object.__setattr__(self, '_data', data)   # dict {fieldname: scalar_value}
        object.__setattr__(self, '_bytes', b'')
        object.__setattr__(self, 'dtype', dtype)

    def __bool__(self):
        return False  # void scalars are always considered zero

    def __getitem__(self, key):
        return object.__getattribute__(self, '_data')[key]

    def __getattr__(self, name):
        # __getattr__ is only called when normal lookup fails
        data = object.__getattribute__(self, '_data')
        if name in data:
            return data[name]
        raise AttributeError(name)

    def __repr__(self):
        data = object.__getattribute__(self, '_data')
        dt = object.__getattribute__(self, 'dtype')
        if dt is None or not data:
            raw = object.__getattribute__(self, '_bytes')
            if raw:
                return 'void({})'.format(repr(raw))
            return 'void()'
        vals = tuple(data[n] for n in dt.names)
        return repr(vals)

    def __iter__(self):
        data = object.__getattribute__(self, '_data')
        dt = object.__getattribute__(self, 'dtype')
        if dt is None or not data:
            return iter([])
        return iter(data[n] for n in dt.names)


class StructuredArray:
    """Python wrapper for _native.StructuredArray (columnar Rust-backed structured array)."""

    def __init__(self, native_arr, py_shape=None):
        object.__setattr__(self, '_native_arr', native_arr)
        dt = _parse_dtype_json(native_arr.dtype)
        object.__setattr__(self, 'dtype', dt)
        # _py_shape: None = use Rust 1D shape; tuple = Python-tracked multi-D shape
        object.__setattr__(self, '_py_shape', tuple(py_shape) if py_shape is not None else None)

    def __getitem__(self, key):
        native = object.__getattribute__(self, '_native_arr')
        dt = object.__getattribute__(self, 'dtype')
        shape = self.shape

        # Tuple key: (i, j) for 2D element access
        if isinstance(key, tuple) and len(shape) > 1:
            if len(key) != len(shape):
                raise IndexError(
                    "too many indices for array: array is {}-dimensional, "
                    "but {} were indexed".format(len(shape), len(key))
                )
            flat = 0
            stride = 1
            for k in _builtin_range(len(shape) - 1, -1, -1):
                flat += key[k] * stride
                stride *= shape[k]
            result = native[flat]
            if isinstance(result, list):
                return void({n: v for n, v in zip(dt.names, result)}, dt)
            return result

        # Integer key on multi-D: return a row (1D StructuredArray)
        if isinstance(key, int) and len(shape) > 1:
            cols = shape[1]  # number of elements per row
            row_native = native[key * cols : (key + 1) * cols]
            if hasattr(row_native, 'field_names'):
                return StructuredArray(row_native)
            # fallback: shouldn't happen
            return row_native

        # All other cases: delegate to existing behavior
        result = native[key]

        # String key: field access — reshape if multi-D, mark as unaligned
        if isinstance(key, str):
            if len(shape) > 1:
                result = result.reshape(shape)
            # Structured field views are unaligned (interleaved memory semantics)
            if hasattr(result, '_set_unaligned'):
                result._set_unaligned()
            return result

        # Integer key (1D) → void scalar
        if isinstance(result, list):
            return void({n: v for n, v in zip(dt.names, result)}, dt)

        # Slice or list-of-strings → StructuredArray
        if hasattr(result, 'field_names'):
            return StructuredArray(result)

        return result

    def __setitem__(self, key, val):
        native = object.__getattribute__(self, '_native_arr')
        # Unwrap StructuredArray wrappers for Rust
        if isinstance(val, StructuredArray):
            val = object.__getattribute__(val, '_native_arr')
        native[key] = val

    def __len__(self):
        return self.shape[0]

    def reshape(self, *new_shape):
        if len(new_shape) == 1 and isinstance(new_shape[0], (list, tuple)):
            new_shape = tuple(new_shape[0])
        else:
            new_shape = tuple(new_shape)
        total = 1
        for s in new_shape:
            total *= s
        native = object.__getattribute__(self, '_native_arr')
        if total != len(native):
            raise ValueError(
                "cannot reshape structured array of size {} into shape {}".format(
                    len(native), new_shape
                )
            )
        # If result is 1D, clear _py_shape so Rust shape is used
        if len(new_shape) == 1:
            return StructuredArray(native)
        return StructuredArray(native, py_shape=new_shape)

    def __iter__(self):
        shape = self.shape
        if len(shape) > 1:
            for i in _builtin_range(shape[0]):
                yield self[i]
            return
        dt = object.__getattribute__(self, 'dtype')
        native = object.__getattribute__(self, '_native_arr')
        for i in _builtin_range(len(native)):
            row_list = native[i]
            yield void({n: v for n, v in zip(dt.names, row_list)}, dt)

    @property
    def shape(self):
        py_shape = object.__getattribute__(self, '_py_shape')
        if py_shape is not None:
            return py_shape
        return tuple(object.__getattribute__(self, '_native_arr').shape)

    @property
    def ndim(self):
        return len(self.shape)

    @property
    def field_names(self):
        return object.__getattribute__(self, '_native_arr').field_names()

    @property
    def flags(self):
        from ._helpers import _ArrayFlags
        return _ArrayFlags(c_contiguous=True, f_contiguous=False)

    def copy(self):
        """Return a deep copy of this structured array."""
        native = object.__getattribute__(self, '_native_arr')
        py_shape = object.__getattribute__(self, '_py_shape')
        # Create a new native array by copying field data
        new_native = native.copy() if hasattr(native, 'copy') else native
        return StructuredArray(new_native, py_shape=py_shape)

    def flatten(self):
        """Return a flattened copy of the structured array."""
        native = object.__getattribute__(self, '_native_arr')
        return StructuredArray(native)

    @property
    def size(self):
        s = self.shape
        result = 1
        for d in s:
            result *= d
        return result

    def setflags(self, write=None, align=None, uic=None):
        """Set array flags (stub for compatibility)."""
        pass

    def astype(self, dtype):
        """Return a copy with the given dtype (stub — returns self for same dtype)."""
        return self.copy()

    def tolist(self):
        """Return the array as a nested Python list of tuples."""
        dt = object.__getattribute__(self, 'dtype')
        return [tuple(row[n] for n in dt.names) for row in self]

    def __repr__(self):
        dt = object.__getattribute__(self, 'dtype')
        rows = list(self)
        return f"StructuredArray({rows}, dtype={dt})"


class recarray:
    """Structured array with attribute-style field access (np.recarray)."""

    def __init__(self, shape, dtype):
        """Create an empty (zero-filled) structured array."""
        if isinstance(shape, int):
            shape = (shape,)
        if len(shape) != 1:
            raise ValueError(
                "recarray only supports 1D arrays; got shape {}".format(shape)
            )
        arr = zeros(shape[0], dtype=dtype)   # returns StructuredArray
        object.__setattr__(self, '_arr', arr)
        object.__setattr__(self, 'dtype', arr.dtype)

    @classmethod
    def _from_structured(cls, structured_arr):
        """Wrap an existing StructuredArray as a recarray (no data copy)."""
        obj = object.__new__(cls)
        object.__setattr__(obj, '_arr', structured_arr)
        object.__setattr__(obj, 'dtype', structured_arr.dtype)
        return obj

    def __getattr__(self, name):
        try:
            arr = object.__getattribute__(self, '_arr')
            dt = object.__getattribute__(self, 'dtype')
        except AttributeError:
            raise AttributeError(name)
        if name in dt.names:
            return arr[name]
        raise AttributeError(name)

    def __setattr__(self, name, value):
        try:
            arr = object.__getattribute__(self, '_arr')
            dt = object.__getattribute__(self, 'dtype')
        except AttributeError:
            object.__setattr__(self, name, value)
            return
        if name in dt.names:
            arr[name] = value
        else:
            object.__setattr__(self, name, value)

    def __getitem__(self, key):
        return object.__getattribute__(self, '_arr')[key]

    def __setitem__(self, key, val):
        object.__getattribute__(self, '_arr')[key] = val

    def __len__(self):
        return len(object.__getattribute__(self, '_arr'))

    def __iter__(self):
        return iter(object.__getattribute__(self, '_arr'))

    @property
    def shape(self):
        return object.__getattribute__(self, '_arr').shape

    @property
    def ndim(self):
        return object.__getattribute__(self, '_arr').ndim


class _RecModule:
    """Stub for numpy.rec submodule."""

    def array(self, data, dtype=None, **kwargs):
        """Create a recarray from data (list of tuples)."""
        arr = array(data, dtype=dtype)   # → StructuredArray or ndarray
        if isinstance(arr, StructuredArray):
            return recarray._from_structured(arr)
        return arr

    def fromarrays(self, arrayList, dtype=None, names=None, **kwargs):
        """Create a recarray from a list of arrays, one per field."""
        if names is not None and dtype is None:
            # Build a structured dtype from the names and inferred column types
            fields = []
            for name, col in zip(names, arrayList):
                col_arr = array(col)
                fields.append((name, str(col_arr.dtype)))
            dtype = globals()['dtype'](fields)
        arr = zeros(len(arrayList[0]), dtype=dtype)
        for name, col in zip(dtype.names, arrayList):
            arr[name] = array(col)
        return recarray._from_structured(arr)

    def fromrecords(self, reclist, dtype=None, names=None, formats=None, **kwargs):
        """Create a recarray from a list of records (tuples)."""
        if dtype is not None:
            arr = array(reclist, dtype=dtype)
            if isinstance(arr, StructuredArray):
                return recarray._from_structured(arr)
            return arr
        if names is not None and formats is not None:
            if isinstance(formats, str):
                formats = [f.strip() for f in formats.split(',')]
            fields = list(zip(names, formats))
            dt = globals()['dtype'](fields)
            arr = array(reclist, dtype=dt)
            if isinstance(arr, StructuredArray):
                return recarray._from_structured(arr)
            return arr
        if names is not None:
            # Infer types from the first record
            if len(reclist) > 0:
                rec0 = reclist[0]
                fields = []
                for i, name in enumerate(names):
                    val = rec0[i] if isinstance(rec0, (tuple, list)) else rec0
                    if isinstance(val, int):
                        fields.append((name, 'int64'))
                    elif isinstance(val, float):
                        fields.append((name, 'float64'))
                    elif isinstance(val, str):
                        fields.append((name, 'U'))
                    elif isinstance(val, bytes):
                        fields.append((name, 'S'))
                    else:
                        fields.append((name, 'float64'))
                dt = globals()['dtype'](fields)
                arr = array(reclist, dtype=dt)
                if isinstance(arr, StructuredArray):
                    return recarray._from_structured(arr)
                return arr
        return array(reclist)


rec = _RecModule()


# --- Aliases ----------------------------------------------------------------

absolute = abs
conjugate = conj

radians = deg2rad
degrees = rad2deg

round_ = around
round = around

mod = remainder
# divmod is exposed as a ufunc (see _ufunc.py); divmod_ is the plain function alias
# divmod = divmod_  # (replaced by ufunc version imported from _ufunc)

special = type('special', (), {
    'gamma': staticmethod(gamma),
    'erf': staticmethod(erf),
    'erfc': staticmethod(erfc),
    'lgamma': staticmethod(lgamma),
    'j0': staticmethod(j0),
    'j1': staticmethod(j1),
    'y0': staticmethod(y0),
    'y1': staticmethod(y1),
})()

# LinAlgError exception — needed by numpy.linalg and tests
class LinAlgError(Exception):
    """Generic Python exception derived class for linalg errors."""
    pass

# Link top-level functions into linalg module
linalg.LinAlgError = LinAlgError
linalg.trace = trace
linalg.cross = cross        # delegate to top-level cross()
linalg.diagonal = diagonal  # delegate to top-level diagonal()
linalg.outer = outer        # delegate to top-level outer()

# Create numpy.linalg._linalg stub submodule for tests that import internals
import types as _types
_linalg_submod = _types.ModuleType("numpy.linalg._linalg")
_linalg_submod.LinAlgError = LinAlgError

def _multi_dot_matrix_chain_order(arrays, return_costs=False):
    """Compute optimal matrix chain multiplication order."""
    n = len(arrays)
    p = [0] * (n + 1)
    for i in range(n):
        shape = arrays[i].shape
        if i == 0:
            p[0] = shape[0]
        p[i + 1] = shape[1] if len(shape) > 1 else 1
    m = [[0] * n for _ in range(n)]
    s = [[0] * n for _ in range(n)]
    for chain_len in range(2, n + 1):
        for i in range(n - chain_len + 1):
            j = i + chain_len - 1
            m[i][j] = float('inf')
            for k in range(i, j):
                q = m[i][k] + m[k + 1][j] + p[i] * p[k + 1] * p[j + 1]
                if q < m[i][j]:
                    m[i][j] = q
                    s[i][j] = k
    if return_costs:
        return s, m
    return s

_linalg_submod._multi_dot_matrix_chain_order = _multi_dot_matrix_chain_order
_sys.modules["numpy.linalg._linalg"] = _linalg_submod

# --- Import submodules so they are accessible as np.xxx ----------------------
import numpy.ma as ma
import numpy.polynomial as polynomial
import numpy._core as _core
import numpy._utils as _utils
import numpy.dtypes as dtypes
import numpy.strings as strings
import numpy.exceptions as exceptions

# --- Additional type aliases -------------------------------------------------
uintc = uint32
intc = int32

# --- Functions commonly imported from numpy ----------------------------------
def shape(a):
    """Return the shape of an array."""
    arr = asarray(a)
    return arr.shape

def normalize_axis_tuple(axis, ndim, argname=None, allow_duplicate=False):
    if isinstance(axis, int):
        axis = (axis,)
    result = []
    for ax in axis:
        if ax < 0:
            ax = ndim + ax
        if ax < 0 or ax >= ndim:
            raise AxisError(ax, ndim, argname)
        result.append(ax)
    if not allow_duplicate and len(set(result)) != len(result):
        raise ValueError("repeated axis")
    return tuple(result)

def normalize_axis_index(axis, ndim, msg_prefix=None):
    if axis < 0:
        axis = ndim + axis
    if axis < 0 or axis >= ndim:
        raise AxisError(axis, ndim)
    return axis

def asmatrix(data, dtype=None):
    return asarray(data, dtype=dtype)

def mask_indices(n, mask_func, k=0):
    a = ones((n, n), dtype=bool_)
    return where(mask_func(a, k))

# --- Sentinel / aliases -----------------------------------------------------
class _NoValue:
    """Sentinel class for missing keyword arguments."""
    def __repr__(self):
        return "<no value>"

cumulative_sum = cumsum
cumulative_prod = cumprod

# --- np.astype (NumPy 2.x function form) ------------------------------------
def astype(x, dtype, copy=None, casting=None):
    """Convert array to specified dtype (NumPy 2.x function form)."""
    # NumPy 2.x requires x to be an ndarray or numpy scalar, not a plain list/tuple
    if not isinstance(x, ndarray) and not hasattr(x, 'dtype'):
        raise TypeError("Input should be a NumPy array or scalar")
    arr = asarray(x)
    if casting is not None and casting in ('safe', 'same_kind', 'no'):
        from numpy._core_types import dtype as _dtype_cls
        src_dt = arr.dtype
        tgt_dt_obj = _dtype_cls(dtype)
        if not can_cast(src_dt, tgt_dt_obj, casting=casting):
            raise TypeError(
                f"Cannot cast array data from {src_dt} to {tgt_dt_obj} "
                f"according to the rule '{casting}'"
            )
    return arr.astype(dtype)

# --- np.from_dlpack stub ----------------------------------------------------
def from_dlpack(x):
    """Stub for DLPack interop — just wraps as array."""
    return asarray(x)

# --- np.isdtype (NumPy 2.x dtype kind check) --------------------------------
def isdtype(dtype_arg, kind):
    """Check if dtype belongs to a specified kind category."""
    # Validate dtype_arg - must be a NumPy dtype, not a string
    if isinstance(dtype_arg, str):
        raise TypeError("dtype_arg must be a NumPy dtype, not a string. "
                        "Use np.dtype('...') to convert.")
    # Normalize dtype_arg to a dtype object
    dt = dtype(dtype_arg)
    dt_name = dt.name if hasattr(dt, 'name') else str(dt)

    # If kind is a tuple, check any
    if isinstance(kind, tuple):
        return any(isdtype(dtype_arg, k) for k in kind)

    # Validate kind argument type
    if not isinstance(kind, (str, type)) and not hasattr(kind, '_scalar_name'):
        raise TypeError("kind argument must be a dtype, a string, or a tuple of these")

    # If kind is an abstract type class, map to the corresponding string kind
    _abstract_map = {
        'bool_': 'bool',
        'signedinteger': 'signed integer',
        'unsignedinteger': 'unsigned integer',
        'integer': 'integral',
        'floating': 'real floating',
        'complexfloating': 'complex floating',
        'number': 'numeric',
    }
    if not isinstance(kind, str):
        # Check if it's an abstract type class from our hierarchy
        kind_scalar = getattr(kind, '_scalar_name', None)
        if kind_scalar in _abstract_map:
            return isdtype(dtype_arg, _abstract_map[kind_scalar])
        # Otherwise treat as concrete dtype for exact match
        kind_dt = dtype(kind)
        kind_name = kind_dt.name if hasattr(kind_dt, 'name') else str(kind_dt)
        return dt_name == kind_name

    # Abstract type hierarchy checks via string kinds
    _signed = {'int8', 'int16', 'int32', 'int64'}
    _unsigned = {'uint8', 'uint16', 'uint32', 'uint64'}
    _real_floating = {'float16', 'float32', 'float64'}
    _complex_floating = {'complex64', 'complex128'}

    if kind == 'bool':
        return dt_name == 'bool'
    elif kind == 'signed integer':
        return dt_name in _signed
    elif kind == 'unsigned integer':
        return dt_name in _unsigned
    elif kind == 'integral':
        return dt_name in (_signed | _unsigned)
    elif kind == 'real floating':
        return dt_name in _real_floating
    elif kind == 'complex floating':
        return dt_name in _complex_floating
    elif kind == 'numeric':
        return dt_name in (_signed | _unsigned | _real_floating | _complex_floating)
    else:
        raise ValueError(f"{kind!r} is not a known kind name. "
                         "Use 'bool', 'signed integer', 'unsigned integer', "
                         "'integral', 'real floating', 'complex floating', "
                         "or 'numeric'.")

# --- Ensure DTypePromotionError is importable from numpy ---------------------
from numpy.exceptions import DTypePromotionError

# --- Helper for structured astype (called from Rust ndarray.astype) ----------
def _astype_structured(arr, dtype_arg):
    """Convert an ndarray to a StructuredArray with the given structured dtype.

    Called from Rust when astype receives a comma-separated dtype string or list dtype.
    """
    from numpy._core_types import dtype as _dtype_cls
    parsed = _dtype_cls(dtype_arg)
    if hasattr(parsed, '_structured') and parsed._structured is not None:
        n = len(arr)
        data = []
        names = parsed.names
        for i in range(n):
            row = arr[i]
            vals = []
            for name in names:
                field_dt, _ = parsed.fields[name]
                fd = str(field_dt)
                if fd in ('float64', 'float32', 'float16') or fd.startswith('f'):
                    vals.append(float(row))
                elif fd in ('int8', 'int16', 'int32', 'int64') or fd.startswith('i'):
                    vals.append(int(row))
                elif fd in ('uint8', 'uint16', 'uint32', 'uint64') or fd.startswith('u'):
                    vals.append(int(row))
                elif fd.startswith('complex') or fd.startswith('c'):
                    vals.append(complex(row))
                else:
                    vals.append(row)
            data.append(tuple(vals))
        return array(data, dtype=dtype_arg)
    # Fallback: just return as-is
    return arr

# --- Module-level __getattr__ for np.bool etc. (NumPy 2.x style) -----------
def __getattr__(name):
    # NumPy 2.x: np.bool → np.bool_, np.int → np.int_, etc.
    _type_aliases = {
        'bool': bool_,
        'int': int_,
        'float': float_,
        'complex': complex_,
        'str': str_,
        'object': object_,
    }
    if name in _type_aliases:
        return _type_aliases[name]
    raise AttributeError(f"module 'numpy' has no attribute '{name}'")
